adicionando modelo e criando app core
Diorgeles/controle_atividades pull request #4
Opened 2019-05-01 17:37 UTC by ArondevIta

Boa tarde, fiz alteração no settings, adicionei a app core e criei os modelos.

2019-05-01 17:44 UTC, Diorgeles requested changes

2019-05-01 17:44 UTC, Diorgeles commented on core/admin.py
> +admin.site.register(Categoria, CategoriaAdmin)
tem um simbolo vermelho no final da linha, isso é o github avisando que é indeal deixar uma linha em branco no final do arquivo, toda IDE tem como ativar isso automaticamente

2019-05-01 17:44 UTC, Diorgeles commented on core/admin.py
> +admin.site.register(Categoria, CategoriaAdmin)
vou deixar dessa forma`admin.site.register` depois lhe mostro um jeito mais elegante de fazer isso, mas por hora ta massa

2019-05-01 17:44 UTC, Diorgeles commented on core/models.py
> +    cat = models.IntegerField()
pode colocar o nome completo mesmo, pense nesse cat solto no meio da view cheia de codigo, vai ficar ruim de identificar

2019-05-01 17:44 UTC, Diorgeles commented on core/models.py
> +    p_acertos = models.DecimalField(max_digits=3, decimal_places=2)
coloca o nome completo, oq é `p`?

2019-05-01 17:47 UTC, ArondevIta commented on core/models.py
> +    cat = models.IntegerField()
ok, vou alterar agora

2019-05-01 17:48 UTC, ArondevIta commented on core/models.py
> +    p_acertos = models.DecimalField(max_digits=3, decimal_places=2)
porcentagem, vou alterar aqui

2019-05-03 14:09 UTC, Diorgeles approved these changes

2019-05-03 14:09 UTC, merged